workflows:
    react-native:
        name: reactnativetest
        instance_type: mac_mini_m1
        environment:
          vars:
            XCODE_WORKSPACE: "nikomobile.xcworkspace"
            XCODE_SCHEME: "nikomobile"
          xcode: latest
          node: 16.14.2
          cocoapods: default
        scripts:
          - name: Install dependencies, Expo CLI and eject app
            script: |
              yarn install
              yarn global add expo-cli
              npx expo prebuild
          - name: Set Info.plist values
            script: |
              PLIST=$FCI_BUILD_DIR/$XCODE_SCHEME/Info.plist
              PLIST_BUDDY=/usr/libexec/PlistBuddy
              $PLIST_BUDDY -c "Add :ITSAppUsesNonExemptEncryption bool false" $PLIST
          - name: Install CocoaPods dependencies
            script: |
              cd ios && pod install
          - name: Build .app
            script: |
              xcodebuild build \
                -workspace "$XCODE_WORKSPACE" \
                -scheme "$XCODE_SCHEME" \
                -sdk iphonesimulator \
                -configuration Debug \
                CODE_SIGN_IDENTITY="" \
                CODE_SIGNING_REQUIRED=NO \
                CODE_SIGNING_ALLOWED=NO 
        artifacts:
          - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.app
        publishing:
          email:
            recipients:
              - ivanleopoldoc@gmail.com

